/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-22-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Constants {
    
    //Login Url 
   //public static final string LOGIN = '/agent/index.php?relogin=YES&session_epoch=1602308994&session_id=8600051&session_name=1602308704_102017562256&VD_campaign=DEMO11';    
   // API 
   /* public static final string STATUS = '/elision-api/main.php?source=test&action=agent_status&stage=csv&header=YES';
    public static final string DISPOSITION = '/elision-api/main.php?source=test&action=status';
    public static final string DISPOSITION_LIST = '/elision-api/main.php?action=list_disposition';
    public static final string HANGUP = '/elision-api/main.php?source=test&action=hangup&value=1&status=NA';
    public static final string LOGOUT = '/elision-api/main.php?source=test&action=logout&value=LOGOUT';    
    public static final string MANUAL_DIAL = '/elision-api/main.php?source=test&action=manual_dial&search=YES&preview=NO&focus=YES';
    public static final string PARK = '/elision-api/main.php?source=test&action=park';
    public static final string PAUSE = '/elision-api/main.php?source=test&action=pause&value=PAUSE';
    public static final string PAUSE_CODE = '/elision-api/main.php?source=test&action=pause_code';
    public static final string PAUSE_LIST = '/elision-api/main.php?action=list_pause_code';
    public static final string RESUME = '/elision-api/main.php?source=test&action=pause&value=RESUME';
    public static final string TRANSFER = '/elision-api/main.php?source=test&action=transfer&function=transfer_conference';
    public static final string TRANSFER_GROUP_LIST = '/elision-api/main.php?action=list_xfergroups';
    public static final string TRANSFER_AGENT_LIST = '/elision-api/main.php?action=list_agents';
    public static final string REGENERATE_SESSION = '/elision-api/main.php?source=test&action=callagent&value=CALL';*/
}